title: "Future Fields"
description: "Assessing crops suitability for fields in the US Southwest."
theme: minima
author:
  name: "Jamie White"
  email: "jqwhite@umich.edu
social_links:
  twitter: jqwhite
  github: jqwhite
